#!/bin/bash

# location of files on physical disk and where results will be written
test_path="$HOME"

# where to do the test - using tmpfs is HIGHLY recommended
ramdisk="/scratch"

# name of the dir containing the preconfigured linux source
source="linux-4.4.248"

# number of times to run benchmark
limit="2"

#####
[[ ! -d "$ramdisk" ]] && mkdir -p "$ramdisk"
[[ ! -f "$test_path"/results.csv ]] && echo "makeflags,n,diff (sec),run date" > "$test_path"/results.csv

calc() {
	diff=$(echo "scale=6; $finish - $start" | bc)
	simpdiff=$(echo "scale=2; $finish - $start" | bc)
	runsleft=$(echo "scale=2; $limit-$x"| bc)
	secleft=$(echo "scale=2; $runsleft*$diff"|bc)
	minleft=$(echo "scale=2; $runsleft*$diff/60"|bc)
	eta=$(date -d "($date) $secleft sec" +%r)
	echo "Run $x/$limit took $simpdiff seconds. ETA: $eta or about $minleft min from now."
	echo "-j$i,$x,$diff,$RUNDATE" >> "$test_path/results.csv"
}

do_make() {
	[[ ! -d $ramdisk/$source ]] && tar axf "$test_path/$source.tar.zst" -C "$ramdisk"
	cd "$ramdisk/$source" || exit

	for i in 9 11; do
		x=0
		# n= limit for each makeflag
		while [[ "$x" -lt "$limit" ]]; do
			x=$(( x + 1 ))
			make -j9 clean &>/dev/null
			RUNDATE=$(date "+%F %T")
			start=$(date +%s.%N)
			unset DISTCC_HOSTS

			export DISTCC_HOSTS=""
			sleep 1s
			#make -j"$i" bzImage CC=distcc CXX=distcc &>/dev/null
			finish=$(date +%s.%N)
			calc
		done
	done
}

do_make
